# Generated by Django 2.0.7 on 2018-07-14 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0002_remove_comment_approved_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profilePic')),
                ('username', models.OneToOneField( to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
