# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20180716_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='profile_pic',
            new_name='profilepic',
        ),
    ]
